### ISSUE TITLE
Schedule은 날짜등록 방식을 다르게 해야할 것 같아요!

### ISSUE THREAD

**Issue by nuri1126** [nuri1126/SWE#5]
Schedule은 날짜등록 방식을 다르게 해야할 것 같아요!
스케줄에 맞는 날짜로 등록되게끔 바꿔야 겠네요!

**Comment by nuri1126** [comment]
이런 식 으로 바꾸는게 좋을 것 같습니다.
	System.out.println("스케줄 날짜를 입력하세요.(yyyy-MM-dd)");
	System.out.print(">>>");
	String inputDate = tempContent.readLine();

**Comment by hyojeonglee** [comment]
네 그럼 Date객체는 필요없겠네요!
