### ISSUE TITLE
누리꺼 fetch하려고 하는데 에러가 뜬다.

### ISSUE THREAD

**Issue by JEunJi** [nuri1126/SWE#6]
혹시 nuri라는 branch에서 작업하고 master랑 merge 제대로 했나 확인 좀 해줘ㅠㅠ

**Comment by jeongy616** [comment]
나도.......에러떠

**Comment by hyojeonglee** [comment]
저도요...add()밖에 없더라구요....!

**Comment by nuri1126** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ맙소사... 고쳤어요!
